// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart'; // dotenv ইম্পোর্ট করা হলো

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_WINDOWS_API_KEY'] ?? '',
    appId: '1:739031407841:web:67ea30a1aefd5c709beba0',
    messagingSenderId: '739031407841',
    projectId: 'lifeos-4f325',
    authDomain: 'lifeos-4f325.firebaseapp.com',
    storageBucket: 'lifeos-4f325.firebasestorage.app',
    measurementId: 'G-1MR97HGTLW',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:739031407841:android:9ca4ccc0d77ca5dc9beba0',
    messagingSenderId: '739031407841',
    projectId: 'lifeos-4f325',
    storageBucket: 'lifeos-4f325.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_MACOS_API_KEY'] ?? '',
    appId: '1:739031407841:ios:ba73112f84b0feb19beba0',
    messagingSenderId: '739031407841',
    projectId: 'lifeos-4f325',
    storageBucket: 'lifeos-4f325.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_MACOS_API_KEY'] ?? '',
    appId: '1:739031407841:ios:ba73112f84b0feb19beba0',
    messagingSenderId: '739031407841',
    projectId: 'lifeos-4f325',
    storageBucket: 'lifeos-4f325.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_WINDOWS_API_KEY'] ?? '',
    appId: '1:739031407841:web:bf06094a4a1a1c2f9beba0',
    messagingSenderId: '739031407841',
    projectId: 'lifeos-4f325',
    authDomain: 'lifeos-4f325.firebaseapp.com',
    storageBucket: 'lifeos-4f325.firebasestorage.app',
    measurementId: 'G-E45F5Z2Z7G',
  );
}